site_name: VCF Networking Encyclopedia
site_description: Technical configuration guide for VCF Networking services in VCF
use_directory_urls: true

theme:
  name: material
  palette:
    # This sets a "VMware-like" blue and white theme
    - scheme: default
      primary: custom
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  logo: assets/VMware_by_Broadcom_White.png
  favicon: assets/VMware_by_Broadcom_White.png  # Optional: uses same logo for browser tab
  features:
    - navigation.tabs              # Top navigation bar
    - navigation.sections          # Grouping in sidebar
    - navigation.top               # "Back to top" button
    - content.code.copy            # "Copy" button on CLI commands
    - navigation.grid              # This is the feature that enables "grid" and "cards"
    - lightbox                     # This is for the image zoom
    - navigation.indexes
    #- navigation.expand            

plugins:
  - search
  - glightbox:
      touchNavigation: true
      loop: false
      zoomable: true
      draggable: true

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition                     # For "Warning" and "Note" boxes
  - pymdownx.details               # For collapsible "Read More" sections
  - pymdownx.superfences           # Better code blocks
  - pymdownx.tabbed:               # For UI vs. API tabs
      alternate_style: true
  - attr_list                      # "grid cards" class to work
  - md_in_html                     # Allows Markdown (the bullets) inside the <div>
  - pymdownx.emoji: # <--- OPTIONAL: Makes the :material-xxx: icons appear
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tilde
  - toc:
      toc_depth: 4

# THIS IS YOUR TABLE OF CONTENTS
nav:
  - VCF Networking Encyclopedia: index.md
  - vCenter Server:
      - Introduction: vcenter/index.md
      - VPC Network Services:
        - VPC Gateway: vcenter/1a-vpc_gateway.md
        - VPC Subnet: vcenter/1b-vpc_subnet.md
        - NAT: vcenter/1c-vpc_nat.md
        - DHCP: vcenter/1d-vpc_DHCP.md
      - VPC Northbound Architecture:
          - VCF Network Infrastructure:
            - Edge Cluster / Node: vcenter/2a-edge.md
            - VNA Cluster / Node: vcenter/2b-vna.md
          - External Connectivity & Services:
            - External Connection: vcenter/3a-external_connection.md
            - Transit Gateway: vcenter/3b-transit_gateway.md
            - IP Block: vcenter/3c-ip_block.md
            - Network Span: vcenter/3d-network_span.md
            - Connectivity Profile: vcenter/3e-connectivity_profile.md
            - Connectivity Policy: vcenter/3f-connectivity_policy.md
  - Supervisor:
      - Introduction: supervisor/index.md
      - VDS + FLB:
          - Installation:
              - Requirements:
                  - Check Requirements: supervisor/1a-requirements.md
              - Supervisor Deployment:
                - Create Supervisor: supervisor/1b1-deploy-supervisor.md
                - Supervisor Access via CLI: supervisor/1b2-access-supervisor.md
              - Namespace Deployment:
                - Create Namespace: supervisor/1c1-deploy-namespace.md
                - Namespace Access via CLI: supervisor/1c2-access-namespace.md
              - K8s Cluster Deployment:
                - Create K8s (CLI): supervisor/1d2-deployment-k8s.md
                - K8s Access via CLI: supervisor/1d3-access-k8s.md
          - Application Deployment:
              - App Deployment (VMs):
                - via CLI: supervisor/1e2-deployment-vms.md
              - App Deployment (K8s): 
                - via CLI: supervisor/1f1-deployment-pods.md
          - Network Services: 
              - VM Load Balancers: supervisor/1g1-network-lb.md
          - Troubleshooting:
              - Packet Walk:
                - N/S External to VIP: supervisor/1h1-packetwalk-ext_vip.md
                - N/S External to VM: supervisor/1h2-packetwalk-ext_vm.md
                - E/W Pod to Pod: supervisor/1h3-packetwalk-pod_pod.md
                - E/W VM to VM: supervisor/1h4-packetwalk-vm_vm.md
      - NSX + DTGW/VNA:
          - Installation:
              - Requirements:
                  - Check Requirements: supervisor/2a-requirements.md
                  - Install Requirements:
                      - NSX Overlay: supervisor/2b1-deploy-NSXOverlay.md
                      - DTGW + VNA: supervisor/2b2-deploy-DTGW_VNA.md
              - Supervisor Deployment:
                - Create Supervisor: supervisor/2c1-deploy-supervisor.md
                - Supervisor Access via CLI: supervisor/2c2-access-supervisor.md
              - Namespace Deployment:
                - Create Namespace: supervisor/2d1-deploy-namespace.md
                - Namespace Access via CLI: supervisor/2d2-access-namespace.md
              - K8s Cluster Deployment:
                - Create K8s (vCenter UI): supervisor/2e1-deployment-k8s.md
                - Create K8s (CLI): supervisor/2e2-deployment-k8s.md
                - K8s Access via CLI: supervisor/2e3-access-k8s.md
          - Application Deployment:
              - App Deployment (VMs):
                - via vCenter UI: supervisor/2f1-deployment-vms.md
                - via CLI: supervisor/2f2-deployment-vms.md
              - App Deployment (K8s): 
                - via CLI: supervisor/2g1-deployment-pods.md
          - Network Services: 
              - Subnets: supervisor/2h1-network-subnet.md
              - SubnetSets: supervisor/2h2-network-subnetset.md
              - Static Routes: supervisor/2h3-network-staticroute.md
              - External IPs: supervisor/2h4-network-externalip.md
              - VM Load Balancers: supervisor/2h5-network-lb.md
          - Troubleshooting:
              - Packet Walk:
                - N/S External to VIP: supervisor/2i1-packetwalk-ext_vip.md
                - N/S External to VM: supervisor/2i2-packetwalk-ext_vm.md
                - E/W Pod to Pod: supervisor/2i3-packetwalk-pod_pod.md
                - E/W VM to VM: supervisor/2i4-packetwalk-vm_vm.md
              - App Access Broken:
                - VIP access down: supervisor/2j1-troubleshooting-vip.md
                - VM access down: supervisor/2j2-troubleshooting-vm.md
                - Pod access down: supervisor/2j3-troubleshooting-pod.md
      - NSX + CTGW/Edge/T0:
          - Installation:
              - Requirements:
                  - Check Requirements: supervisor/3a-requirements.md
                  - Install Requirements:
                      - NSX Overlay: supervisor/3b1-deploy-NSXOverlay.md
                      - CTGW + Edge + T0: supervisor/3b2-deploy-CTGW_Edge_T0.md
              - Supervisor Deployment:
                - Create Supervisor: supervisor/3c1-deploy-supervisor.md
                - Supervisor Access via CLI: supervisor/3c2-access-supervisor.md
              - Namespace Deployment:
                - Create Namespace: supervisor/3d1-deploy-namespace.md
                - Namespace Access via CLI: supervisor/3d2-access-namespace.md
              - K8s Cluster Deployment:
                - Create K8s (vCenter UI): supervisor/3e1-deployment-k8s.md
                - Create K8s (CLI): supervisor/3e2-deployment-k8s.md
                - K8s Access via CLI: supervisor/3e3-access-k8s.md
          - Application Deployment:
              - App Deployment (VMs):
                - via vCenter UI: supervisor/3f1-deployment-vms.md
                - via CLI: supervisor/3f2-deployment-vms.md
              - App Deployment (K8s): 
                - via CLI: supervisor/3g1-deployment-pods.md
          - Network Services: 
              - Subnets: supervisor/3h1-network-subnet.md
              - SubnetSets: supervisor/3h2-network-subnetset.md
              - Static Routes: supervisor/3h3-network-staticroute.md
              - External IPs: supervisor/3h4-network-externalip.md
              - VM Load Balancers: supervisor/3h5-network-lb.md
          - Troubleshooting:
              - Packet Walk:
                - N/S External to VIP: supervisor/3i1-packetwalk-ext_vip.md
                - N/S External to VM: supervisor/3i2-packetwalk-ext_vm.md
                - E/W Pod to Pod: supervisor/3i3-packetwalk-pod_pod.md
                - E/W VM to VM: supervisor/3i4-packetwalk-vm_vm.md
              - App Access Broken:
                - VIP access down: supervisor/3j1-troubleshooting-vip.md
                - VM access down: supervisor/3j2-troubleshooting-vm.md
                - Pod access down: supervisor/3j3-troubleshooting-pod.md

